import { Nav, MobileNav } from "@components/nav";

import "../fonts/Inter/inter.css";
import "../fonts/Greycliff/greycliff.css";
import "../fonts/CodeSaver/codesaver.css";
import "../styles/index.css";
import "../styles/prism-synthwave.css";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <link rel="shortcut icon" href="/favicon.svg" />
            </head>
            <body>
                <Nav />
                <MobileNav />
                <div className="layout-page container mx-auto p-4 md:px-10">
                    {children}
                </div>
            </body>
        </html>
    )
}
